Feature/#3 회원가입
threeback/kicketing-back pull request #10
Opened 2024-04-08 19:48 UTC by cottonrose1011

## 📄 Summary
> #3
* 회원가입 기능
* 구글 SMTP 사용한 이메일 인증 기능

## 🙋🏻 More
> 
* 달려보자고 !!

2024-04-08 23:50 UTC, pwrwpw requested changes
뭔가 부분부분 테스트코드가 어디는 영어로 어디는 한글로 쓰고 있는거 같은데 한번 같이 얘기해보는게 좋을 것 같습니다~!!

수고하셨어요

2024-04-08 23:50 UTC, pwrwpw commented on src/main/java/tback/kicketingback/email/service/EmailAuthService.java
> +	void saveCode(String email, String code);
이 윗 부분 아래쪽은 띄어져있는데 서로 안 맞는거 같아요

2024-04-08 23:50 UTC, pwrwpw commented on src/main/java/tback/kicketingback/global/encode/PasswordEncoderSHA256.java
> +            throw new RuntimeException("Error encoding password", e);
이부분 저희 했던 것처럼 커스텀 예외 보내도 되지않을까요

2024-04-08 23:50 UTC, pwrwpw commented on src/main/java/tback/kicketingback/user/signup/controller/SignUpController.java
> +			throw new AlreadyEmailAuthCompleteException();
예외를 서비스에서 던지도록 바꿀수 있을 것 같은데 어떻게 생각하세요?

2024-04-09 09:37 UTC, CodingApe9 commented on src/main/java/tback/kicketingback/global/encode/PasswordEncoderSHA256.java
> +            MessageDigest digest = MessageDigest.getInstance("SHA-256");
이대로 사용하는 것도 가독성이 좋지만
리터럴 "SHA-256" 보다는 상수로 사용하는게 좋을 것 같아요.

2024-04-09 09:37 UTC, CodingApe9 commented on src/main/java/tback/kicketingback/user/domain/User.java
>  		return Pattern.matches("^[_a-z0-9-]+(.[_a-z0-9-]+)*@(?:\\w+\\.)+\\w+$", email);
정규식도 DEFAULT_PASSWORD_REX 같은 이름으로 상수로 등록해 가독성을 높이면 좋을 것 같아요.
비밀번호 변경같은 다른 기능에서도 사용할 수 있게 추상화를 통해 정규식 정책을 분리해서 의존하는 것도 괜찮아 보이네요.

2024-04-09 09:37 UTC, CodingApe9 commented on src/main/java/tback/kicketingback/user/domain/User.java
> +		return Pattern.matches("^[가-힣a-zA-Z]{2,20}$", name);
이 부분도 위 커멘트와 동일한 의견입니다!

2024-04-09 09:37 UTC, CodingApe9 commented on src/main/java/tback/kicketingback/user/exception/exceptions/MismatchEmailAuthCodeException.java
> +		super("인증 번호가 틀립니다.");
어떤 메시지는 "~~~ 틀립니다." 처럼 끝나지만 어떤 메시지는 "~~~ 실패"로 끝나네요.
예외 메시지를 일관성 있게 작성할 수 있도록 다 같이 컨벤션을 정하는게 좋을 것 같아요.

2024-04-09 09:37 UTC, CodingApe9 commented on src/main/java/tback/kicketingback/user/signup/controller/SignUpController.java
> +			throw new AlreadyEmailAuthCompleteException();
동의합니다.
해당 로직을 서비스 안으로 이전하는게 좋아 보이네요.

2024-04-09 09:37 UTC, CodingApe9 commented on src/main/java/tback/kicketingback/user/signup/controller/SignUpController.java
> +		int code = NumberUtil.createRandomCode6();
지금보니 난수생성 기능을 재활용 할 수 있을지 궁금하네요.
회원가입 이메일 서비스 안으로 이전해도 괜찮을까요?

2024-04-09 09:37 UTC, CodingApe9 commented on src/main/java/tback/kicketingback/user/signup/controller/SignUpController.java
> +	public ResponseEntity<Void> emailCode(@RequestBody EmailCodeRequest emailCodeRequest) {
제가 작성한 코드지만 다른 api에 비해 이 api는 컨트롤러단이 너무 두껍다고 생각합니다.
혹시 다른 좋은 구조가 있을까요?

2024-04-09 09:37 UTC, CodingApe9 commented on src/main/java/tback/kicketingback/user/signup/service/DefaultSignUpService.java
> +		return Pattern.matches("^(?=.*[0-9])(?=.*[a-z])(?=.*[^a-zA-Z0-9]).{8,12}$", password);
형식 정책같은 이름으로 정규식을 한 곳으로 모으는게 좋을 것 같네요.
다들 어떻게 생각하세요?

2024-04-09 09:37 UTC, CodingApe9 commented on src/main/java/tback/kicketingback/user/signup/service/SignUpEmailService.java
> +			message.setSubject(AUTH_CODE_EMAIL_SUBJECT);  // 제목 설정
충분히 의미가 전달되는 코드라고 생각합니다.
주석을 삭제해도 좋을 것 같아요 ㅎㅎ

2024-04-09 09:37 UTC, CodingApe9 commented on src/main/java/tback/kicketingback/user/signup/service/SignUpEmailService.java
> +		body.append("<h3> 감사합니다. </h3>");
리터럴로 사용하는 것보다는 따로 분리하는게 좋지 않을까요?

2024-04-09 09:37 UTC, CodingApe9 commented on src/main/java/tback/kicketingback/user/signup/service/SignUpEmailService.java
> +	@Transactional
특별히 트랜잭션 어노테이션을 사용한 이유가 있을까요?

2024-04-09 09:37 UTC, CodingApe9 commented on src/main/java/tback/kicketingback/user/signup/utils/NumberUtil.java
> +	// 랜덤 인증 코드 생성
주석이 없어도 충분히 이해되는 메서드라고 생각합니다!!

2024-04-09 09:37 UTC, CodingApe9 commented on src/test/java/tback/kicketingback/global/encode/PasswordEncoderSHA256Test.java
> +		encoded = PasswordEncoderSHA256.encode(rawPassword);
굳이 선언과 대입을 분리하지 않아도 좋을 것 같아요. ㅎㅎ

2024-04-10 08:01 UTC, cottonrose1011 commented on src/main/java/tback/kicketingback/email/service/EmailAuthService.java
> +	void saveCode(String email, String code);
반영했습니다~

2024-04-10 08:02 UTC, cottonrose1011 commented on src/main/java/tback/kicketingback/global/encode/PasswordEncoderSHA256.java
> +            throw new RuntimeException("Error encoding password", e);
PasswordEncodeException 만들어 예외처리했습니다.

2024-04-10 08:28 UTC, cottonrose1011 commented on src/main/java/tback/kicketingback/user/domain/User.java
>  		return Pattern.matches("^[_a-z0-9-]+(.[_a-z0-9-]+)*@(?:\\w+\\.)+\\w+$", email);
정규식 상수화 완료했습니다!

2024-04-10 08:28 UTC, cottonrose1011 commented on src/main/java/tback/kicketingback/global/encode/PasswordEncoderSHA256.java
> +            MessageDigest digest = MessageDigest.getInstance("SHA-256");
알고리즘 리터럴이 아닌 상수 사용 반영했습니다

2024-04-10 08:30 UTC, cottonrose1011 commented on src/main/java/tback/kicketingback/user/domain/User.java
> +		return Pattern.matches("^[가-힣a-zA-Z]{2,20}$", name);
위와 동일하게 적용하였습니다.

2024-04-10 08:40 UTC, cottonrose1011 commented on src/main/java/tback/kicketingback/user/signup/controller/SignUpController.java
> +		int code = NumberUtil.createRandomCode6();
정책상 인증을 추가하는 경우에 재사용 여지가 있어 보여요

2024-04-10 08:51 UTC, cottonrose1011 commented on src/test/java/tback/kicketingback/global/encode/PasswordEncoderSHA256Test.java
> +		encoded = PasswordEncoderSHA256.encode(rawPassword);
한 줄로 합쳤습니다!

2024-04-10 09:06 UTC, cottonrose1011 commented on src/main/java/tback/kicketingback/user/signup/utils/NumberUtil.java
> +	// 랜덤 인증 코드 생성
삭제했습니다!

2024-04-10 09:07 UTC, cottonrose1011 commented on src/main/java/tback/kicketingback/user/signup/service/SignUpEmailService.java
> +		body.append("<h3> 감사합니다. </h3>");
* 오버라이딩을 하고 메소드의 인자를 사용하기 때문에 바깥 필드 상수를 사용할 수 없어 메소드 안에서 스트링 상수를 선언하는 것과 크게 달라보이지 않았어요. 
* 분리 원하신다면 반영하겠습니다!

2024-04-10 09:11 UTC, cottonrose1011 commented on src/main/java/tback/kicketingback/user/signup/service/SignUpEmailService.java
> +	@Transactional
메세지 생성 + 전송의 과정이 한 트랜잭션에 묶이지 않은 이상 사용이 필수적은 아니라고 생각합니다.

2024-04-10 09:15 UTC, cottonrose1011 commented on src/main/java/tback/kicketingback/user/exception/exceptions/MismatchEmailAuthCodeException.java
> +		super("인증 번호가 틀립니다.");
"~~니다."체로 컨벤션 일관성 유지 시켰습니다.

2024-04-10 09:20 UTC, cottonrose1011 commented on src/main/java/tback/kicketingback/user/signup/service/SignUpEmailService.java
> +			message.setSubject(AUTH_CODE_EMAIL_SUBJECT);  // 제목 설정
삭제했습니다!

2024-04-10 09:20 UTC, cottonrose1011 commented on src/main/java/tback/kicketingback/user/signup/service/DefaultSignUpService.java
> +		return Pattern.matches("^(?=.*[0-9])(?=.*[a-z])(?=.*[^a-zA-Z0-9]).{8,12}$", password);
User 내에 있는게 한 곳으로 모으는 것이라 생각합니다!

2024-04-10 09:21 UTC, cottonrose1011 commented on src/main/java/tback/kicketingback/user/signup/controller/SignUpController.java
> +	public ResponseEntity<Void> emailCode(@RequestBody EmailCodeRequest emailCodeRequest) {
"Service단에서 생성/전송 을 한 번에 처리하고 번호를 유지한다"가 아니면 현행유지가 좋아보입니다.

2024-04-11 01:23 UTC, CodingApe9 commented on src/main/java/tback/kicketingback/user/domain/User.java
> +		return Pattern.matches(DEFAULT_PASSWORD_REGEX, email);
이메일을 비밀번호 정규식으로 확인하고 있어요!!
정규식을 확인해보니 이메일 정규식은 맞는 것 같은데 상수명을 잘못 작성하신 것 같아요!

2024-04-11 02:03 UTC, CodingApe9 approved these changes

2024-04-11 03:10 UTC, pwrwpw approved these changes
다들 고생하셨습니다~!

2024-04-11 03:10 UTC, merged